-- Notificação de título vencido passa a ser **por cliente**, não por título.
--
-- O sino do vendedor ficava com uma linha por parcela atrasada: um cliente com
-- doze parcelas ocupava as doze primeiras posições do feed e escondia todo o
-- resto. A varredura (`NotificacoesVarreduraService.titulosVencidos`) agora
-- agrupa por cliente e grava `referenciaId` = id do **cliente**, com a rota da
-- posição do cliente.
--
-- As linhas do desenho antigo têm `referenciaId` = id do **título**, que não
-- casa mais com nada: não seriam atualizadas pela nova varredura nem sairiam
-- do feed quando a parcela fosse paga. São apagadas em vez de marcadas como
-- lidas — ninguém as leu, e "lida" é um fato do usuário, não um jeito de
-- esconder registro. A varredura seguinte regrava o que ainda estiver vencido,
-- já agrupado.
--
-- Sem RLS no caminho: esta migration roda com o role dono (`plataforma`), e as
-- tabelas não têm FORCE ROW LEVEL SECURITY.
DELETE FROM "notificacoes" WHERE "tipo" = 'titulo_vencido';
