import { z } from "zod";
import { auditFieldsSchema, booleanQueryParam, paginationQuerySchema } from "./common";

// Espelhos read-only do ERP: sem create/update — os dados entram só pelo
// import (e no futuro pela API externa de manutenção).

export const notaSaidaSchema = z.object({
  id: z.string().uuid(),
  empresaId: z.string().uuid(),
  codigoLegado: z.number().int().nullable(),
  clienteId: z.string().uuid().nullable(),
  vendedorId: z.string().uuid().nullable(),
  condicaoPagamentoId: z.string().uuid().nullable(),
  numero: z.string(),
  serie: z.string().nullable(),
  especieFiscal: z.string().nullable(),
  tipo: z.string().nullable(),
  dtEmissao: z.string().datetime().nullable(),
  ano: z.number().int().nullable(),
  mes: z.number().int().nullable(),
  vlrBruto: z.number(),
  vlrMercadoria: z.number(),
  vlrItens: z.number(),
  vlrDesconto: z.number(),
  vlrIcms: z.number(),
  vlrIpi: z.number(),
  vlrFrete: z.number(),
  vlrDevolucao: z.number(),
  chaveNfe: z.string().nullable(),
  dtNfe: z.string().datetime().nullable(),
  mensagem: z.string().nullable(),
  comodato: z.boolean(),
  ativo: z.boolean(),
  ...auditFieldsSchema.shape,
});
export type NotaSaida = z.infer<typeof notaSaidaSchema>;

export const notaSaidaQuerySchema = paginationQuerySchema.extend({
  ativo: booleanQueryParam,
  clienteId: z.string().uuid().optional(),
  vendedorId: z.string().uuid().optional(),
  comodato: booleanQueryParam,
  tipo: z.string().trim().max(1).optional(),
  ano: z.coerce.number().int().optional(),
  mes: z.coerce.number().int().min(1).max(12).optional(),
});
export type NotaSaidaQuery = z.infer<typeof notaSaidaQuerySchema>;

export const notaSaidaItemSchema = z.object({
  id: z.string().uuid(),
  empresaId: z.string().uuid(),
  notaSaidaId: z.string().uuid(),
  codigoLegado: z.number().int().nullable(),
  clienteId: z.string().uuid().nullable(),
  vendedorId: z.string().uuid().nullable(),
  produtoId: z.string().uuid().nullable(),
  item: z.number().int().nullable(),
  dtEmissao: z.string().datetime().nullable(),
  ano: z.number().int().nullable(),
  mes: z.number().int().nullable(),
  cfop: z.string().nullable(),
  tipo: z.string().nullable(),
  quantidade: z.number(),
  vlrUnitario: z.number(),
  vlrTabela: z.number().nullable(),
  percDesconto: z.number().nullable(),
  vlrDesconto: z.number(),
  vlrTotal: z.number(),
  quantidadeDev: z.number().nullable(),
  vlrDev: z.number().nullable(),
  peso: z.number().nullable(),
  comodato: z.boolean(),
  ativo: z.boolean(),
  ...auditFieldsSchema.shape,
});
export type NotaSaidaItem = z.infer<typeof notaSaidaItemSchema>;

export const NOTA_SAIDA_EXAMPLE: NotaSaida = {
  id: "9c0d1e2f-3a4b-4c5d-6e7f-8091a2b3c4d5",
  empresaId: "7b2f2f64-9b1c-4a86-9d3e-1f4a5b6c7d8e",
  codigoLegado: 116067,
  clienteId: "d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f70",
  vendedorId: "b7c2c1de-4a45-4b8a-9f2e-6a1d6c1e9f10",
  condicaoPagamentoId: "1a2b3c4d-5e6f-4a7b-8c9d-0e1f2a3b4c5d",
  numero: "000116067",
  serie: "1",
  especieFiscal: "SPED",
  tipo: "N",
  dtEmissao: "2026-06-30T00:00:00.000Z",
  ano: 2026,
  mes: 6,
  vlrBruto: 1260.5,
  vlrMercadoria: 1200,
  vlrItens: 1200,
  vlrDesconto: 0,
  vlrIcms: 204,
  vlrIpi: 0,
  vlrFrete: 60.5,
  vlrDevolucao: 0,
  chaveNfe: "50260600000000000191550010001160671000116060",
  dtNfe: "2026-06-30T00:00:00.000Z",
  mensagem: null,
  comodato: false,
  ativo: true,
  createdAt: "2026-07-24T12:00:00.000Z",
  updatedAt: "2026-07-24T12:00:00.000Z",
  createdBy: null,
  updatedBy: null,
};

export const NOTA_SAIDA_ITEM_EXAMPLE: NotaSaidaItem = {
  id: "0d1e2f3a-4b5c-4d6e-7f80-91a2b3c4d5e6",
  empresaId: "7b2f2f64-9b1c-4a86-9d3e-1f4a5b6c7d8e",
  notaSaidaId: "9c0d1e2f-3a4b-4c5d-6e7f-8091a2b3c4d5",
  codigoLegado: 402118,
  clienteId: "d4e5f6a7-8b9c-4d0e-9f1a-2b3c4d5e6f70",
  vendedorId: "b7c2c1de-4a45-4b8a-9f2e-6a1d6c1e9f10",
  produtoId: "c1d2e3f4-5a6b-4c7d-8e9f-0a1b2c3d4e5f",
  item: 1,
  dtEmissao: "2026-06-30T00:00:00.000Z",
  ano: 2026,
  mes: 6,
  cfop: "5102",
  tipo: "N",
  quantidade: 3,
  vlrUnitario: 42,
  vlrTabela: 42,
  percDesconto: 0,
  vlrDesconto: 0,
  vlrTotal: 126,
  quantidadeDev: null,
  vlrDev: null,
  peso: 15.6,
  comodato: false,
  ativo: true,
  createdAt: "2026-07-24T12:00:00.000Z",
  updatedAt: "2026-07-24T12:00:00.000Z",
  createdBy: null,
  updatedBy: null,
};
